### ISSUE TITLE
Caching CF api request's result at log level 1 doesen't works

### ISSUE THREAD

**Issue by zhorvath83** [docker-hotio/docker-cloudflare-ddns#15]
I deployed your container with LOG_LEVEL=1 environment variable setting. I noticed that the PiHole log contains a lot of name resolution for the api.cloudflare.com domain. It has been found that caching of API request results does not work at log level one and no cache files are created on the docker volume. So at log level one every IP check generates a CF API call to verify the current IP address. At log level two and three everything works normal (with talkative log).

Is this a planned operation at log level one? The readme doesn't mention this side effect of log level one.

**Comment by hotio** [comment]
They should all behave the same, it's just log output

**Comment by hotio** [comment]
can you try out the new release when it's available....

**Comment by hotio** [comment]
And?

**Comment by zhorvath83** [comment]
Thanks, at the new release everything works great with log level one !
